### PR TITLE
Patch ML 1.0.0.216

### PR DESCRIPTION
**Pull request by astog**
- Fixes issue with some lenses not being imported
- Removed CQUI minimap size setting
- Readded Citizen management area lens on hover and in screen. Uses appeal lens as base rather than government. Note: The final implementation is still hacky because Firaxis made it that appeal lens is blocked during citizen management mode. So to force it there is refresh of lenses that causes a flicker of yields. This only occurs when in city screen, not during hover. It can still be disabled from CQUI settings panel. But I want to find a better solution to this in future. Maybe @Azurency or other CQUI devs could find it.
- Removed some deprecated LuaEvents calls.
- Moved most print statements to CQUI `debug_print`

### CODE REVIEW

**Comment by astog** [comment]
@Azurency Don't merge this yet, noticed an issue with district placement. Working on it now 😄

**Comment by astog** [comment]
Should be good now, you are welcome to play test this and let me know if you encounter any issues

**Comment by Azurency** [comment]
Nice I will test all that and take a look at this yield flicker.

**Comment by Azurency** [comment]
I was able to fix the lens weird reset. I'll merge this and push my fix just after. It was an event in `wordlinput.lua` that was resetting the lens to `ManageCitizen` every time.

**Pull request merged**
