### PR TITLE
CQUI Fall Update

### PR DESCRIPTION
**Pull request by Timmeey86**

### CODE REVIEW

**Comment by Azurency** [comment]
This looks great, good job 👍. Thank you for helping.
I think you're planning to continue to work on this branch so I'm not merging it now. Let me know if that's not the case.

**Comment by Timmeey86** [comment]
@Azurency Changed another file, but won't have time for more for the next ~20 hours. Feel free to merge now or postpone.
Note that I'm only merging what Firaxis changed without evaluating if this requires CQUI to be adapted - I don't know enough of the CQUI Code just yet.

**Comment by Timmeey86** [comment]
@Azurency I'm gonna stop updating files for a while. If you merge my changes and the ones of the other contributors to the Fall branch, I'd start testing CQUI features instead and we would probably have a clearer picture of what still needs to be done.

**Comment by Timmeey86** [comment]
@Azurency I updated my branch from the Azurency/fall-2017 branch, let me know if this leads to any kind of trouble for the pull request - I'm very experienced in svn but still a git noob

**Comment by oerms** [comment]
I think, you selected the wrong target branch for the merge.
> Timmeey86 wants to merge 17 commits into Azurency:master from Timmeey86:master

**Comment by Timmeey86** [comment]
@oerms Indeed, I changed the base here on github.com, did this do the trick?

**Comment by Azurency** [comment]
I'll definitely take a look at this very soon and test everything.
Could you please rebase your branch on the latest fall-2017 before I merge ?

**Comment by Azurency** [comment]
Oh, you merged, I want a **rebase** because I cleaned the history and squashed the commits of Sparrow into a single one (and they're showing in your branch because you merged them before)

#### What is a rebase?
Rebase basically rewrite your history by replaying your commit on top of another branch, if you wish to learn more https://git-scm.com/docs/git-rebase is a great documentation.

#### How to rebase?
The command will look like this (for you): 
`git rebase azurency(or the name you gave to my remote)/fall-2017 master`

I've tested it for you by fetching your branch and try to rebase.
⚠️ You will have some conflicts, first with civ6common (accept the HEAD version) then again on  civ6common (again accept HEAD version) then on the diplomacyribbon.xml (accept the HEAD version).

Now you have a clean git history, just force push this to your upstream branch.

If it's too complicated for you or you don't have the time, I could push the rebased branch myself and create a pull request with your commits, but it's fun to try and learn 😉 

(you also used master instead of another branch in your fork, that's not a problem here but it's something you want to avoid, either by committing on the same branch as the one you aim to target or creating a new branch from the one you aim to target)

**Comment by Timmeey86** [comment]
I was about to write about the conflict. I've already added you as a collaborator but will try to do it myself based on your explanation.

**Comment by Timmeey86** [comment]
Hum.. did the rebase according to your explanation, but now my pull request also contains sparrow's changes. I guess that's not intended? Do I have to revert the merges first or something?

**Comment by Azurency** [comment]
Of course sorry, you merged so it replayed the merged commit as well, saved you some time and created you a new branch https://github.com/Timmeey86/CQUI_Community-Edition/tree/Timmeey86-fall-2017 with the cherry-picked relevant commits

**Comment by Timmeey86** [comment]
Alright.. I guess the hard way is the best way when it comes to learning ;-) I opened #162 from the new branch for a clean start

**Pull request closed without merging**
