### PR TITLE
Espionage patch. Fixes #234.

### LINKED ISSUE #234: Espionage screens list non-available targets
Both the espionage overview and the target selector screens list cities, and display district icons even for cities/districts where the target has been disabled. Example: you are looking for Space ports to disrupt with your spy. Your enemy civ has built the Space port in three of his cities, and two of them are already disabled; both the overview and the selector will list ALL three cities and show the Space port icon as if they were available targets. The user has to go to each city and visually confirm on the map that the target is disabled or if it is a valid, enabled target.

### PR DESCRIPTION
**Pull request by ricanuck**
Fixes #234. Shows only districts that are valid targets.

### CODE REVIEW

**Comment by ricanuck** [comment]
Third commit changes the espionageoverview.lua file for the better... the solution now is more elegant and uses the hasDistrict() support function, which also allows the overview to show specialty districts that were not shown before (i.e., Hansa, Mbanza, etc).

**Comment by Azurency** [comment]
Thx for this fix. But it would be better to post this patch in @astog repo here : https://github.com/astog/BES. Then we'll merge it here.

**Comment by ricanuck** [comment]
Sorry but no, CQUI is my arena... he could also grab it from here if he is interested. Not that they are a huge amount of lines anyways...

**Comment by Azurency** [comment]
Sorry that's not how open source works. I don't care if it's "you're arena" or whatever, BES is an integration from @astog, please respect it.

**Comment by ricanuck** [comment]
Partially true (and I did not mean ownership of anything when I said "my arena", I meant "the sandbox where I chose to play"). In example: our "integration" of IDS is MUCH better than the original. If I change anything there now, I would not go to the original creator, who is AFAIK not even maintaining it anymore... I would change our custom version.
Granted, astog is still maintaining his work, but there is a chance that he will not like something we do, and thus what do we do? Not change something we like to, or customize our version?
Lastly, please do not disrespect me (and all our previous work) by insinuating that I disrespect other modders. Nothing farther from the truth, and even suggesting it is insulting to me.

**Comment by ricanuck** [comment]
As for the patch itself: it is here, at your disposal. It makes the espionage screen considerably better, and micromanagement of the spies much more efficient. If you want to block/delay the merge for whatever reasons you may have (which I fail to see and/or understand), then you are basically denying the CQUI users a better espionage screen. That is on you, man.
I have it in my setup, and it works nicely, and makes espionage management less of a chore; I don't need to go to each listed city to check if they really have my target available anymore.
If you want to neglect that nice "little" change to the users, up to you.

**Comment by Azurency** [comment]
If anything, the way you always react make me want to take some distance with the mod... I "inherited" it because I enjoyed working on it, and not to get worked up.
I don't understand you, I'm just asking a simple thing that seems really reasonable and right thing to do for this situation (I don't believe @astog will refuse this good modification) and yet (again) you're overreacting. 
I'm always welcoming any contribution from you or anyone and I expect from the contributors to be open-minded, understanding and to show goodwill. Now if you don't understand that, you will not be surprised if I don't answer you anymore in the future.

**Comment by ricanuck** [comment]
and I am overreacting? Okay... and insulting once again (do I have to copy-paste your last words, or can you just re-read your last post?)...
Anyways, answer or not a piacere, I am not the owner of the mod and neither are you, but you put yourself in a position to act as if you were (ONLY person to approve merges). If you want more help, and more open-mindedness, how about stop acting as if you were the owner and just approve good modifications, regardless of who the author is? Yes, I know, Chao put himself in the same position, but he WAS the creator and owner of this mod, and will forever be, no matter what he generously put in the license files.
And stop insulting, please. That does not say much about you.

**Comment by Azurency** [comment]
https://github.com/astog/BES/pull/3

**Comment by ricanuck** [comment]
I will make it easy for you: if you are so open-minded, good-willed and only interested in the community, OPEN this repository to more people with merge attributions. There are a few here that can help, some of them veterans from the original CQUI. I remind you. you are NOT the owner of this mod. Remove yourself from the position of sole "owner/merger" of this repository, and we will never have to face this nonsense again.
Oh, and yes, you will be relieved from having to answer to me.

**Comment by oerms** [comment]
I would like to suggest to define how to deal with changes to the integrations to avoid misunderstandings in the future.
Also, please bear in mind, that the tone of written language might be misunderstood, especially in the case of a foreign language. Let's keep cool and relaxed.

**Pull request merged**
