### PR TITLE
Adds missing block of code to diplo ribbon.

### PR DESCRIPTION
**Pull request by ricanuck**
The merge missed an important block of code related to the relationship tooltips. This corrects the issue.

### CODE REVIEW

**Comment by Azurency** [comment]
hmm 🤔 I thought I moved all of this inside `leadericon.lua` with the summer patch (https://github.com/Azurency/CQUI_Community-Edition/commit/eb426d2668181c3dc181d567d57351e6073d46b9) , what exactly is not working ? I'll check tomorrow. I might have missed some things or yes deleted too much

**Comment by ricanuck** [comment]
tooltips disappeared with every call to Updateleaders(), which was called by almost every possible event. Result was that the tooltip was not there most of the time, and that was not the intended behavior nor the behavior previous to the Summer patch. With this update it works as it did before, and the tooltip is ON all the time.

**Comment by ricanuck** [comment]
I think I found why: apparently, setting the tooltip works on the INSTANCE but not on the LEADERICON class, which is what you call to inside Leadericon.lua... why? Firaxis.
So, inside the code, the extended relationship tooltip works fine as long as it called for the instance of the icon.

**Comment by Azurency** [comment]
Sorry but, I tested it and I don't get what's not working ? 
When `UpdateLeaders()` is called, even in the firetuner, I still have the extended relationship tooltips shown correctly on hovering the relationship icon of the leader. Is it that the number are not correct ?

**Comment by ricanuck** [comment]
Whenever I enter any diplo screen, and then go back out to main screen, tooltips are not there anymore until I use the other ribbon function to enforce it (CTRL Mouse Over any leader). It might be that I am testing with an ongoing game, but I doubt it. Can you try doing what I said? Enter a diplo screen, get out and check if the tooltips are still there.

**Comment by Azurency** [comment]
They're still there when I enter a diplo screen and exit. I'm also in an ongoing game. I'll  try to start a new one and ask other people to test it too.

**Comment by Timmeey86** [comment]
I cannot reproduce the issue either, tried with and without the changes in this branch, first without restarting the game, then after restarting the game. I am playing in windowed mode however, maybe that makes a difference.

**Comment by ricanuck** [comment]
I just tested with a new game, and the problem is there. So it's not the ongoing game, it's the code. Why it behaves differently for you, no idea. But the old code is faultproof, so I would just re-add it now for quicker release, and then we can try and find out why it behaves inconsistently.

**Comment by ricanuck** [comment]
Just to be clear, we are talking about the relationship tooltips that should appear when hovering over the attitude face at the bottom left of a leader icon (the list of diplo modifiers in red/green...

**Comment by ricanuck** [comment]
Tested once again, still not working.
Basically, when I load the game, the tooltips are not there. By default, with the new code, they just don't show up. Only after I CTRL-mouse over any leader icon, they start working because the code for that function uses the call to instance. As soon as an UpdateLeaders() is called, the tooltips disappear again.
Please merge this PR to make the tooltip work consistently until we find the cause of the inconsistency.

**Comment by Timmeey86** [comment]
I was just able to reproduce this in a multiplayer game hosted by a friend.

**Comment by sparrow8332** [comment]
After 16 test games i can confirm in 1 game i did reproduce this. Its not common but it still exists

**Comment by Oscar-IronTower** [comment]
I have the same issue in all my games.

**Comment by Oscar-IronTower** [comment]
Merging this change fixed it.

**Comment by ricanuck** [comment]
Multiple confirmations, yet it is not being merged... explain please?

**Comment by sparrow8332** [comment]
@ricanuck - azurency is most likely really busy with work and family mate.

**Comment by Azurency** [comment]
"explain please?" 🤔 It was a very busy week and I was hoping to have more time to try to figure out what happens with the leader icon but anyway I will merge this...

**Comment by ricanuck** [comment]
Thanks for explaining. I explained myself a lot at the beginning of this request. Specifically, I suggested that if we have a working version of anything, we should always prioritize merging it into the master, and only then, and if time allows it, search for a more "elegant" solution. The mod working 100% should always be well above any "perfect", technical solution; this was one good case to show just that.
That's all. No need to be offended.

**Pull request merged**
