### PR TITLE
September 2019 Update mod fixes

### PR DESCRIPTION
**Pull request by carlos-witek**
I have expanded further what has been started by @scrubdaddytm here https://github.com/Azurency/CQUI_Community-Edition/pull/405 . I hope @scrubdaddytm won't mind that I have basically copied his solution rather than extending from his repo. I have figured out that I prefer to have my own copy of @Azurency repo and also it was way simpler to do.

It looks like it makes the mod work for me on my computer. Anyone cares top verify on theirs?
Here are the steps to manually install my changes on Windows:
1. run Civ 6 and from main menu got to `Additional Content` > `Mods`
2. make sure all the previous versions of CQUI Mod are removed (if you have installed via Steam make sure you unsubscribe there as well)
3. exit Civ 6 and make sure it is not running
4. got to your `Documents\My Games\Sid Meier's Civilization VI\Mods` folder
5. download the changes https://github.com/carlos-witek/CQUI_Community-Edition/archive/expansion2-summer-update.zip to that folder and unzip it (right click and press `Extract All...` and confirm the pop up which should create new folder `CQUI_Community-Edition-expansion2-summer-update` in your `Documents\My Games\Sid Meier's Civilization VI\Mods`)
6. run Civ 6 and from main menu got to `Additional Content` > `Mods` to manually enable the mod

### CODE REVIEW

**Comment by marekpetras** [comment]
works for me, great work mate, thanks

**Comment by nukeajs** [comment]
Seems like everything that's there is working. But a couple of things are not enabled -- namely better report screens. Oh and when you get enough GPPs to get a great person, the recruit and pass buttons are blocking the description of what they specifically do. Not a huge issue, but an annoyance nonetheless.

**Comment by wayneb64** [comment]
I didn't even notice the GPP button issue or the reports issue, neither really hurt gameplay. What I did notice is that so far anyway the lenses are all working fine which did impact my gameplay.

**Comment by Gyrofalcon** [comment]
Had some wired issues in the Trading Screen. AI had a few of my cities in the AI-list, and I had all AI cities in my list. Could be a conflict with some other mod (not running Better Trading Screen)? If no one has seen it with CQUI, then it is in my end. And I can confirm conflict with "Z Unit Marks", but the rest of the 63-mod'ed-game are running with only CTD when quieting or re-loading a game.
I approve this version and it works for me.

**Comment by scrubdaddytm** [comment]
you're a hero <3

**Comment by wayneb64** [comment]
Something I noticed recently is the map tacks seem to have reverted somehow with this fix. The standard set are all there but I seem to recall there was some kind of upgrade to them with some nice ones they added to the game that I don't see anymore. My memory is lousy but I swear that one of them was a nice barbarian camp icon that was red and not the crappy one that is the same color as your civ.

**Comment by nukeajs** [comment]
If you piece-meal carlos-witek's version with a couple of other mods, you basically get the full CQUI with just a few oddities. I mentioned the reports screens not showing up, for example. However, if you use both CQUI and seperate Better Reports Screen mod, it works just fine. The only issue I'm having after slapping together a bunch of mods is the Great People buttons.

**Comment by Flactine** [comment]
Minimap is broken

**Comment by tmgm** [comment]
The minimap cqui popup settings does not seem to work for any settings. Anyone know how i can otherwise turn off yields always showing? Civ 6 keybindings apparently overwritten by mod settings. Thanks for all the hard work.

**Comment by wayneb64** [comment]
The yield setting is backwards in CQUI. I want them always on so I set it to off in CQUI.

**Comment by an-accident** [comment]
I have the same problem @Gyrofalcon mentioned. In deal screen cities are usually incorectly named. Adding them to the trade shows the real names but it's not always possible: sometimes clicking just does nothing, even if the city hiding under the button should be tradeable (e.g. not capital).
Here an example:
Zrzut ekranu (292)
Cities are completly dis-named. Most of them named after my capital - Qusqu. As you can see, clicking one one of them puts in the central list the right city. and by 'the right' I mean the one that should alphabetically be in that position in the left list. But, for example, adding any of the following two Qusqu's to the trade is not possible.
Other symptoms:
-list does not depend on which leader I'm trying to deal with
-changing city name does not impact list (even next turn), only loosing/aquiring cities

By the way: issue is present with only CQUI enabled (version from first post but was also present before).

**Comment by nukeajs** [comment]
I have this CQUI, Better Report Screens, and a couple of UI unrelated mods enabled and mine works almost perfectly ... strange.

**Comment by wayneb64** [comment]
The only thing broken for me is the citizens tab in the city panel.

**Comment by nukeajs** [comment]
It's interesting that it seems people are getting different things that are not working as intended.

I'm loving that my issue is a minor one :)

**Comment by bobc** [comment]
I've also got an issue with wrong city names in the deal screen, and the issue with Great People buttons.

Generally stuff I can live with...

**Comment by darioty** [comment]
Is this an update only or will it work alone? I got issues with buying units with gold as well as the deal screen. I was hoping it works when I install the main branch then overwrite with this one.

**Comment by Gyrofalcon** [comment]
> Is this an update only or will it work alone? I got issues with buying units with gold as well as the deal screen. I was hoping it works when I install the main branch then overwrite with this one.

Delete everything you have of old copies of CQUI. Both in SteamWorkshop folder and in Mods-folder, not just un-sub the mod on Steam. Then copy this version, found in OP in this tread, to the Mods-folder.

**Comment by MrUnlad** [comment]
Will this be updated? There are still issues with the city names in the deal screen and tile yield icons not turning on or off. Thanks.

**Comment by OmnipotentStomper** [comment]
I'm using the version from this thread for my current game. In the Diplomacy Ribbon, (top of main screen), I'm only getting the 3 stats that CQUI has always had, not the 7 that the base game now includes.
In the standard game Interface Options page, I have "Show Yields in HUD Ribbon" set to "Always Show"
In the CQUI options, if I leave the "Show the Diplomacy Ribbon" option off, I get no yields,
if I turn it on, I just get the 3.
How can I get the full ribbon that the base game has?

**Comment by Slapstick2244** [comment]
This isn't that big of a deal but the mini map has stop working again, no idea why as I don't have any other mods that conflict with it.

**Comment by vfauth** [comment]
Works very well, except for City States:
- I see only one city state int he panel
- I can't send any envoy

**Comment by OmnipotentStomper** [comment]
> Works very well, except for City States:
> 
> * I see only one city state int he panel
> * I can't send any envoy

Those features are working fine for me.
You might double check that you cleaned out old versions when you installed this one.

**Comment by rogerthehart** [comment]
Most of this fix works great for me. I do have a couple of minor annoyances:
- Every GP icon shows as Great Admiral
- Notify messages are shown old style: large and in the middle of the screen

**Comment by alexeyOnGitHub** [comment]
hey guys, is anyone willing to drive this to completion? it pains me that every time there is an update to the base game this awesome mod gets broken for many months. the base game UI is too painful to use IMO (death by a thousand mouse clicks).

**Comment by Goobye** [comment]
> 
> 
> I have the same problem @Gyrofalcon mentioned. In deal screen cities are usually incorectly named. Adding them to the trade shows the real names but it's not always possible: sometimes clicking just does nothing, even if the city hiding under the button should be tradeable (e.g. not capital).
> Here an example:
> Zrzut ekranu (292)
> Cities are completly dis-named. Most of them named after my capital - Qusqu. As you can see, clicking one one of them puts in the central list the right city. and by 'the right' I mean the one that should alphabetically be in that position in the left list. But, for example, adding any of the following two Qusqu's to the trade is not possible.
> Other symptoms:
> -list does not depend on which leader I'm trying to deal with
> -changing city name does not impact list (even next turn), only loosing/aquiring cities
> 
> By the way: issue is present with only CQUI enabled (version from first post but was also present before).

I have this issue

Has there been a solution for this?

**Review by bwach — APPROVED** [review]

**Comment by pointcache** [comment]
As a workaround, delete everything from mods folder, just leave this CQUI.modinfo
```xml
<?xml version="1.0" encoding="utf-8"?>
<Mod id="1d44b5e7-753e-405b-af24-5ee634ec8a01" version="1">

  <!-- Basic Mod Information -->
  <Properties>
    <AffectsSavedGames>0</AffectsSavedGames>
    <Name>Community Quick User Interface</Name>
    <Teaser>CQUI</Teaser>
    <Description>Community Quick User Interface MOD was Formally CQUI Mod [NEWLINE]and is now being updated and improved by its community</Description>
    <CompatibleVersions>2.0</CompatibleVersions>
  </Properties>

</Mod>

```

restart the game, go to peace screen and do your thing.

**Comment by camk16** [comment]
Does not work. Envoy Problem.

**Comment by carlos-witek** [comment]
Hey Everyone.

First of all thank you all for your participation. I'm glad to hear that it helped some people to enjoy the mod again. Sorry to hear that this does not solve all the problems - especially the big one with Diplomacy screen.

Here is few things that you all should have in mind:

1. 

Without approval of the owner of the repo @Azurency this cannot be merged and made properly available. At the same time I do not have permission from him to distribute the code. So we are stuck until owner makes his move.

2.
Frankly I have not enough skill/knowledge to make the big fixes. I have tried but I must admit that I do not understand the structure of the mode nor how it works. What I have done so far was just copy the fixes done before. If there are any more experience moders around here I would appreciate help.

Sorry Everyone that I have no better news.

**Comment by vvolodin** [comment]
The code has MIT license... just sayin'

**Comment by the-m4a** [comment]
Hey everyone -
I started with the changes from @carlos-witek and made additional fixes, which I will post in a new PR and see what I can do about creating a new repo in order to try and revive this project.

Edit: link to PR with updated version that can be downloaded:
https://github.com/Azurency/CQUI_Community-Edition/pull/415

Significant fixes:
- Cities appear correctly in diplomacy trade screen
  - NOTE: Need to investigate if there still exists a problem with the diplomacy "demand" screen.
- Resource Icon toggle in mini-map works correctly
- Resource icons should do solid / transparent / hidden correctly now (depending on setting)
- Amenities calculation in City screen should work now

**Pull request merged**
