### PR TITLE
Fall 2017 Compatibility Update

### PR DESCRIPTION
**Pull request by astog**
## Changelog
1. Makes BTS compatible with Fall 2017 update. Fixes issues will pulldown sizes and adds religious pressure icons.
2. Makes ML compatible with Fall 2017 update. Fixes issues with the builder lens, adds the religion lens changes.
3. Changed tab length for two files in ML. Those commits only change tab length. That is the reason for the huge amount line deletions and additions. If you need me to change the tab length to 4, I can push a commit for that. Let me know.

_Will work on BES later..._

### CODE REVIEW

**Comment by astog** [comment]
@Azurency Don't merge this yet. Apparently there is a bug with TradeRouteChooser screen going out of screen. I should have this fixed this week.

**Comment by Azurency** [comment]
Ok, I'll wait. If you need any help, do not hesitate to ask, I could take a look at it.

**Comment by Azurency** [comment]
Also hovering a city when you are in some lenses, reset the graphics. It's not an indented behavior as hovering a city happens often when you move on the map. 

The concerned lenses : 
- Religion
- Continent
- Government

**Comment by astog** [comment]
@Azurency Both those bugs should be fixed now. Hopefully everything else works. 😄 👍

**Comment by Azurency** [comment]
Nice 👍 ! You'll add your update to BES in this pull request or should I merge it now ?

**Comment by astog** [comment]
I can add BES here I guess. I am looking into it now. That way all three are updated at the same time.

**Comment by astog** [comment]
@Azurency and others, can you check this pull request, specifically the BTS part. I have gotten comments saying they can't start domestic routes or the route choose screen is only showing one route, but it is working for me, so I want to know how to recreate that bug and try and fix it.

**Comment by Azurency** [comment]
I remember testing the changes yesterday and everything was fine. I can't check today, but I'll give it a look tomorrow evening

**Comment by astog** [comment]
@Azurency With this all my mods should be updated. If bugs do arise, I'll post a separate pull request.

**Comment by Azurency** [comment]
@astog It's merged 🎉 thx a lot for updating your mods so fast and making this pull request !

**Pull request merged**
