### PR TITLE
September 2019 Update mod fixes v2 (includes fixes from PR #407)

### PR DESCRIPTION
**Pull request by the-m4a**
These are fixes in addition to those already made by @carlos-witek ([#407](https://github.com/Azurency/CQUI_Community-Edition/pull/407)) and @scrubdaddytm ([#405](https://github.com/Azurency/CQUI_Community-Edition/pull/405)).

**To use:**
1. Run Civ 6 and from main menu go to Additional Content > Mods
2. Ensure all the previous versions of CQUI Mod are disabled and removed
  a. If you have CQUI installed via Steam subscription, make sure you unsubscribe
3. Exit Civ 6 and make sure it is not running
4. Go to your _Documents\My Games\Sid Meier's Civilization VI\Mods_ folder
5. Download the CQUI Mod source files with the changes from my branch:
[https://github.com/the-m4a/CQUI_Community-Edition/archive/master.zip](https://github.com/the-m4a/CQUI_Community-Edition/archive/master.zip)
6. Copy the zip file (but do NOT unzip yet!) to _Documents\My Games\Sid Meier's Civilization VI\Mods_ folder
7. (Optional, but recommended): rename master.zip to CQUI.zip
(This is simply to have the unzipped files show up in a folder named _CQUI_)
8. Right-click on the .zip file in the _Documents\My Games\Sid Meier's Civilization VI\Mods_ folder and choose _Extract All_
9. Start Civ 6, the Mod should show as visible in the Additional Content -> Mods folder.  Enable the mod and enjoy.

**Fixes in addition the version created by carlos-witek (9/27/19)**
- Cities appear correctly in diplomacy trade screen
  - NOTE: Need to investigate if there still exists a problem with the diplomacy "demand" screen.
- Resource Icon toggle in mini-map works correctly
- Resource icons should do solid / transparent / hidden correctly now (depending on setting)
- Amenities calculation in City screen should work now
- Updated all DarkenLightenColor calls to UI.DarkenLightenColor (as global version is depreciated)
- Code formatting in CityBannerManager.lua (confirmed no other changes to this file)

**Additional Notes**
- As much as I love the CQUI mod and many of the Civ6 mods, I very often do not have the time to do this kind of work.  However, with the stay-at-home stuff going on and my desire to have CQUI functional, I was able to dig in and get it back to a looks-to-be working order.
- I have played games for the last week or so with these changes and have not seen additional issues, **however**, I have not done extensive testing of various modes or with other mods, so I expect that I may have missed something.
- I will do what I can to try and make fixes identified by other folks
- If we happen to not hear from @Azurency anytime soon, I'll look into publishing the mod again so everyone can subscribe to it instead of having to use this .zip file method.

### CODE REVIEW

**Comment by Azurency** [comment]
Hi, I want to thank all of those who contributed to fix CQUI 🎉👏 . 

There are a lot of dedicated people out there to care about the mod. I'm finally having so time to merge everything and take a look at it. I'm having a little more free time also right now (maybe not for long).
I think I'll even enjoy playing a game of civ with this CQUI fix 😉.

For the steam repo, we'll need to ask @sparrow8332 to push the update out there because I'm not the owner of the workshop.

**Comment by the-m4a** [comment]
Huzzah!  Thanks for the push and merge - updating the original post to reflect this.

**Comment by the-m4a** [comment]
@Azurency do the changes in the expansion2 branch need to be merged into master before they'll be reflected in the version on the Steam workshop?

**Comment by ollyprice87** [comment]
Just tired, soon as I meet my first Civ the overview dies. I can still select units but that's it. None of the keyboard shortcuts work. 

Using DX12 so might try on DX11

**Comment by ollyprice87** [comment]
DX11 works fine. I also disabled the "extended diplomacy" mod I was running too.

**Comment by rainonej** [comment]
I just recently found this mod. It's amazing! I can't believe it ever went into disrepair. Thanks for trying to fix it. 

Anyways, I followed the manual download instructions and everything seemed to work well. The lenses worked and everything. But it's impossible to assign envoys to city states. The city state screen just doesn't work. Although I am using CIVITAS city-states expanded mod. Is this a known issue/conflict? Or do you want me to give you a full mod list and any sort of log files?

**Comment by ollyprice87** [comment]
Disable CIVITAS mod and try again. Think it
Should work.

**Comment by Etdashou** [comment]
Hi,
This mod is wonderful.

However, when I load a saved game, it doesn't work/appear.

When I start a new game, it does work.

Any workaround? Fix?

**Comment by wayneb64** [comment]
No, you must have the mod enabled when you start a new game and it will remain enabled for that game. If they release a game update that breaks the mod it will also break that game.

**Comment by Etdashou** [comment]
> No, you must have the mod enabled when you start a new game and it will remain enabled for that game. If they release a game update that breaks the mod it will also break that game.

I was able to make it work for an already started game by doing the following:
```
Open CQUI.modinfo file.
Goto line 6 and change
the
<AffectsSavedGames>1</AffectsSavedGames>
to
<AffectsSavedGames>0</AffectsSavedGames>
and save the file.
```

This come from a discussion in the Steam Workshop page. Not sure if it is bad to do so... but I was able to play yesterday all good.

**Comment by jerrywgray** [comment]
The policy selection screen seems bugged. I can only scroll the list of filters, not the policies themselves. Makes it hard to select policies late game.

**Comment by borgheshia** [comment]
> 
> 
> I just recently found this mod. It's amazing! I can't believe it ever went into disrepair. Thanks for trying to fix it.
> 
> Anyways, I followed the manual download instructions and everything seemed to work well. The lenses worked and everything. But it's impossible to assign envoys to city states. The city state screen just doesn't work. Although I am using CIVITAS city-states expanded mod. Is this a known issue/conflict? Or do you want me to give you a full mod list and any sort of log files?

Hi everybody ! 
1st, thx you very much for your hard word and dedication.
Indeed CIVITAS city-states expanded  and this version are making the city state UI bug. I'm loving both of them, and would appreciate so much to make them work together. Have fun guys ;)

**Pull request merged**
