### PR TITLE
Update More Lenses integration to 4.2

### PR DESCRIPTION
**Pull request by scrubdaddytm**
Boils down to a merge of [More Lenses 4.2](https://github.com/astog/MoreLenses/releases/tag/4.2).

Fixes issues mentioned in #404

lenses

### CODE REVIEW

**Review by saadsidqui — APPROVED** [review]

**Comment by Sorxus** [comment]
Hi!
For one lens there is written "$LensName$" and isn't active. On the other hand there is missing lens for Barbarians and Worker...  :(

**Comment by Sorxus** [comment]
Correction:
There is something weird, once there are lenses: 
- Religion, Continent, Appeal, Settler, Government, Political, Tourism, Empire, Loyalty, Power, Barbarian, Wonders, Naturalist, Builder, Scout, $LensName$, City Overlap, Resources, 

and under some conditions (I couldn't say when) there are only these Lenses: 
- Religion, Continent, Appeal, Settler, Government, Political, Tourism, Empire, Loyalty, Power, $LensName$, City Overlap, Resources.

So in second case there are missing Barbarian, Wonders, Naturalist, Builder and Scout. It seems like a some strange bug...

**Comment by wayneb64** [comment]
The worst lense issue is the worker lense going away, any hope of a fix for that?

Anyone try the September patch yet with this version?

I hope CQUI isn't dead, Firaxis is putting out lots of good patches but giving up CQUI to get them is something I really don't want to do.

**Comment by Sorxus** [comment]
Play with September patch, fix issues with Espionage Screen and Trade Screen with Astog's September remedy:
https://github.com/astog/BES/releases
https://github.com/astog/BTS/releases
Unpack them in corresponding place in Integration folder:
... \Sid Meier's Civilization 6\DLC\CQUI_Community-Edition-update-more-lenses\Integrations\

**Comment by Sorxus** [comment]
I see carlos-witek made fix after my "instructions". Good!  ;)

**Comment by carlos-witek** [comment]
@the-m4a so this PR has already been merged to `expansion2` branch as part of your https://github.com/Azurency/CQUI_Community-Edition/pull/415, correct? Perhaps we could close it then? Is it only @scrubdaddytm that can do it?

**Pull request closed without merging**
