### PR TITLE
Merge Expansion2 branch into master

### PR DESCRIPTION
**Pull request by alexeyOnGitHub**
I have tried "expansion2" branch with the current Civ 6 version. looks good.
given that the current code in "master" branch won't work with the latest Civ 6 anyway, I see no harm in merging "expansion2" branch into "master" at this point, even if it may potentially benefit from some additional cleanup later. 
let's merge this to "master", cut a release and push it to Steam Workshop?

### CODE REVIEW

**Comment by alexeyOnGitHub** [comment]
@Azurency hey Antoine, can you please merge this?

**Comment by danieldonaldson** [comment]
@alexeyOnGitHub Hey bud, I think I managed to find a way to get it onto steam workshop, if you want to give it a try?

**Comment by lionel42** [comment]
> @Azurency hey Antoine, can you please merge this?

New release (21. May) of the game has broken a lot of the mod's functionality. 
It would not be effective to merge it now.

**Comment by alexeyOnGitHub** [comment]
the old version (in master) was totally broken for a long time, so merging would not harm. and the longer we keep a branch open (with the pending PR), the harder it would be for other developers to propose additional changes, that would probably need to be based on the changes in this branch.
so not merging this will most likely make it ever harder for people to submit fixes for the new Frontier-related issues. 
keeping multiple branches with complex relations between them is just not viable for this project.

**Comment by alexeyOnGitHub** [comment]
I forked this repo and merged the PR here:
https://github.com/civfanatics/CQUI_Community-Edition

**Pull request closed without merging**
