### PR TITLE
Fix techtree for Spring 2018 update

### PR DESCRIPTION
**Pull request by pspjuth**
This merges the game changes to techtree.lua.

### CODE REVIEW

**Comment by pspjuth** [comment]
This also closes #329

**Comment by Azurency** [comment]
Great ! I see no issue, thank you for you contribution and for helping with the update 👍. 
And congratulation for your first contribution on cqui 🎉

**Comment by Xerus2000** [comment]
Wondering the same. The Steam-version of the mod is completely broken right now due to this issue...

**Comment by ihendriks** [comment]
It won't be merged until the mod is actually functional, and not semi-functional like it is now. Gotta wait until Azurency has time to check some of the other stuff as well.

Sorry about the hassle, but there's one actual maintainer atm and until others step up that won't change any time soon either.

**Pull request merged**
